### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/awesome-scifi#1]
- [x] Linkify all the novels. To where though? Amazon? GoodReads? I'm leaning towards GoodRead. Thoughts?
- [x] Add short description on what the novel is about and why you should read it.
- [x] Contributing guidelines, requiring the above.

**Comment by danilopopeye** [comment]
+1 GoodReads! :smiley:

Mainly because they have links to several book shops!

![screen shot 2015-01-21 at 5 40 58 pm](https://cloud.githubusercontent.com/assets/27297/5843583/afd2929c-a194-11e4-9297-9a4d8741228b.png)

**Comment by sindresorhus** [comment]
@danielhusar already done ;)

**Comment by hiddentao** [comment]
Should the list of book names be in alphabetical order? Or ordered by rating?

**Comment by sindresorhus** [comment]
@hiddentao Doesn't really matter. Rating isn't a good indication whether people would like the book or not, but I guess it's a bit better than alphabetical, so lets go with sorted by rating.

**Comment by ocombe** [comment]
We might want to add tags or something so that we know what kind of scifi it is (space opera, cyberpunk, post apocalyptic, ...).
Or maybe we can order by category, then by rating (but one book might fall into 2 categories...).

**Comment by jpkempf** [comment]
Ordering books by rating would mean that books belonging to the same series probably won't appear in the right order (or even next to each other at all) anymore. Maybe rank the first part of any series by rating and then add the rest of the series directly below regardless of their rating?

**Comment by sindresorhus** [comment]
> Maybe rank the first part of any series by rating and then add the rest of the series directly below regardless of their rating?

:+1: 

Also :+1: to categories. Can you open a new issue about that?

**Comment by ocombe** [comment]
I'll do it (2 more days until I finish here and change job, it's not like I'm gonna do a lot of work today anyway) !

**Comment by ocombe** [comment]
@sindresorhus do you prefer me to add category tags to existing suggestions, or to reorder them by categories ?

**Comment by sindresorhus** [comment]
Reorder by category.

**Comment by ocombe** [comment]
Okay let's do that!

**Comment by ocombe** [comment]
Done, I also added the summaries.
And I added emoji but they don't seem to work :(
I don't know why...

**Comment by ocombe** [comment]
I know, that's the model I used... and it works in issues :fire:

**Comment by sindresorhus** [comment]
@ocombe Thanks for adding all this. Must have taken a lot of time. I've did some formatting improvements and added a TOC. Let me know if you have any other ideas on what we can do to improve it ;)

I emailed GitHub support about the emoji thing.

**Comment by ocombe** [comment]
Ah yes much better with your formatting and the TOC!
We may want to add more space between categories ?
Also we could sort by rating in each category ?

And it only took me like what.. 2 hours? :smile:

**Comment by sindresorhus** [comment]
> We may want to add more space between categories ?

:+1: 

> Also we could sort by rating in each category ?

:+1:

**Comment by sindresorhus** [comment]
From GitHub:

> We've temporarily disabled Emoji rendering in overly large documents because of performance issues. This is a temporary measure while we work on improving the performance of our rendering pipeline. We will restore this functionality as soon as possible. Apologies for the inconvenience.
